### ISSUE TITLE
Add Option to Import Events Into Google Calendar

### ISSUE THREAD

**Issue by felix-seifert** [kthaisociety/website#165]
When you go to an event details' page, you currently have the option to integrate the event in your local calendar.

Some people might not have a local calendar app or their system does not integrate the calendar app correctly. As Google calendar seems to be a standard for many people, visitors should get the option to import the event online directly into the Google calendar without the hassle of dealing with their local environment.

**Comment by oriolclosa** [comment]
Great idea, we can easily add a Google calendar link instead! Do you feel like we should keep both or just replace the ICS file download with the link? Thinking about how to differentiate them with Font Awesome if we keep both.

**Comment by oriolclosa** [comment]
Great idea, we can easily add a Google calendar link instead! Do you feel like we should keep both or just replace the ICS file download with the link? Thinking about how to differentiate them with Font Awesome if we keep both.

**Comment by felix-seifert** [comment]
Definitely both. We should not support the monopoly of Google and support only their calendar.

You could try to make the calendar options more obvious. On first sight, I was thinking that there is no calendar option and the the calendar icon is just another social network. Maybe, you can enhance the calendar icons similarly to the "Facebook event" button. Maybe like "Add to local calendar" and "Add to Google calendar".

**Comment by oriolclosa** [comment]
Sounds great! Specially the part of not supporting Google's monopoly 😄. I've been wanting to move that "Facebook event" button so I think I'll group them together and with a bit of text more descriptive so that you can see something like "Download ICS file", "Add it to Google Calendar" and "Facebook event" in the same row.

**Comment by oriolclosa** [comment]
Changed this accordingly in #166.

![image](https://user-images.githubusercontent.com/10714286/119534026-bf703000-bd86-11eb-8506-4498cea9aa76.png)
