### ISSUE TITLE
Link tree with social media and others

### ISSUE THREAD

**Issue by oriolclosa** [kthaisociety/website#226]
Christos suggested a page where we could all of our media sites similar as to the following site.

http://ieee.upatras.gr/links

**Comment by oriolclosa** [comment]
I think this page should contain different sections...

- Links that can be added from admin with a title, link and perhaps a FontAwesome selectable icon.
- Latest articles (perhaps like two only).
- Current future events if any.
- Links to other social media.

**Comment by simonebonato** [comment]
Ok I'll try to make it and then maybe after a call we can discuss the details and see what to do
