### ISSUE TITLE
Prevent registering with @kthais.com email domain

### ISSUE THREAD

**Issue by isakcodes** [kthaisociety/website#254]
A common misunderstanding among new members signing up is that they should register a new xxx@kthais.com email. This email doesn't exist and so the email is returned to me.

Can we block that in the form? So you get an error or warning when trying to register with a kthais.com email.

Small fix that makes a difference.

**Comment by oriolclosa** [comment]
How do team members sign up then?

**Comment by danielbenedi6** [comment]
I think he means they are trying to create a new account at kthais.com, but they should use 'Login with Google '

**Comment by isakcodes** [comment]
I mean non-team members just registering as normal members do this. Thinking they will get a new xxx@kthais.com account
