### ISSUE TITLE
Registration fields are reset to defaults when inappropriate

### ISSUE THREAD

**Issue by isakcodes** [kthaisociety/website#55]
**The minor issue:** When registering as a user, if you forget to enter passwords or enter unmatching passwords or a similar error, the fields for `University` and `Programme` reset to their defaults.

**The problem with it**: A user may fill in the form and see the notification to correct the passwords. But not noticing that the selections for University and Programme have changed press Register, thereby giving us the wrong data.

**Related suggestion**: Have the warning give a full account of the missing fields in a list. Make it more clear to the user what is left to fill in.

**Comment by isakcodes** [comment]
Here's the responsible code for defaulting back to KTH as university.

https://github.com/kthaisociety/website/blob/7ace9ed60036dbb52f29883b9fe4ae7247db4ea8/user/templates/register.html#L61

**Comment by isakcodes** [comment]
**Suggestion:** cache all the fields in the form when clicking register so that when you go back, they are guaranteed to be intact.

**Comment by isakcodes** [comment]
I tried just removing the associated `{%%}` logic `user/templates/register.html` but got issues with what data was picked up and sent from the form. Bug was that it tried to cast e.g. `"Karolinska Institute'` to int here: 
https://github.com/kthaisociety/website/blob/7ace9ed60036dbb52f29883b9fe4ae7247db4ea8/user/views.py#L194
It obviously expected the corresponding integer value, but got the text name instead for some reason because of that change..

**Comment by oriolclosa** [comment]
I actually fixed this while reviewing #54 so when that one gets merged we can close this!
